#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ChadderTest.Droid.Resource", IsApplication=true)]

namespace ChadderTest.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ChadderLib.Droid.Resource.Drawable.ic_default_face = global::ChadderTest.Droid.Resource.Drawable.ic_default_face;
			global::ChadderLib.Droid.Resource.String.AccountPasswordChange = global::ChadderTest.Droid.Resource.String.AccountPasswordChange;
			global::ChadderLib.Droid.Resource.String.AccountPasswordChangeConfirm = global::ChadderTest.Droid.Resource.String.AccountPasswordChangeConfirm;
			global::ChadderLib.Droid.Resource.String.AccountPasswordChangeLoading = global::ChadderTest.Droid.Resource.String.AccountPasswordChangeLoading;
			global::ChadderLib.Droid.Resource.String.AccountPasswordChangeMessage = global::ChadderTest.Droid.Resource.String.AccountPasswordChangeMessage;
			global::ChadderLib.Droid.Resource.String.AccountPasswordChangeTitle = global::ChadderTest.Droid.Resource.String.AccountPasswordChangeTitle;
			global::ChadderLib.Droid.Resource.String.AddContactLink = global::ChadderTest.Droid.Resource.String.AddContactLink;
			global::ChadderLib.Droid.Resource.String.ApplicationName = global::ChadderTest.Droid.Resource.String.ApplicationName;
			global::ChadderLib.Droid.Resource.String.ApplicationTitle = global::ChadderTest.Droid.Resource.String.ApplicationTitle;
			global::ChadderLib.Droid.Resource.String.CONNECTION_ERROR = global::ChadderTest.Droid.Resource.String.CONNECTION_ERROR;
			global::ChadderLib.Droid.Resource.String.ChatsTabTitle = global::ChadderTest.Droid.Resource.String.ChatsTabTitle;
			global::ChadderLib.Droid.Resource.String.CommonAlert = global::ChadderTest.Droid.Resource.String.CommonAlert;
			global::ChadderLib.Droid.Resource.String.CommonBack = global::ChadderTest.Droid.Resource.String.CommonBack;
			global::ChadderLib.Droid.Resource.String.CommonCancel = global::ChadderTest.Droid.Resource.String.CommonCancel;
			global::ChadderLib.Droid.Resource.String.CommonError = global::ChadderTest.Droid.Resource.String.CommonError;
			global::ChadderLib.Droid.Resource.String.CommonLoading = global::ChadderTest.Droid.Resource.String.CommonLoading;
			global::ChadderLib.Droid.Resource.String.CommonOkay = global::ChadderTest.Droid.Resource.String.CommonOkay;
			global::ChadderLib.Droid.Resource.String.CommonUpdating = global::ChadderTest.Droid.Resource.String.CommonUpdating;
			global::ChadderLib.Droid.Resource.String.CommonWarning = global::ChadderTest.Droid.Resource.String.CommonWarning;
			global::ChadderLib.Droid.Resource.String.ConnectionNotAvailable = global::ChadderTest.Droid.Resource.String.ConnectionNotAvailable;
			global::ChadderLib.Droid.Resource.String.ContactBlock = global::ChadderTest.Droid.Resource.String.ContactBlock;
			global::ChadderLib.Droid.Resource.String.ContactFindTitle = global::ChadderTest.Droid.Resource.String.ContactFindTitle;
			global::ChadderLib.Droid.Resource.String.ContactKeyReset = global::ChadderTest.Droid.Resource.String.ContactKeyReset;
			global::ChadderLib.Droid.Resource.String.ContactKeyWrong = global::ChadderTest.Droid.Resource.String.ContactKeyWrong;
			global::ChadderLib.Droid.Resource.String.ContactKeyWrongTitle = global::ChadderTest.Droid.Resource.String.ContactKeyWrongTitle;
			global::ChadderLib.Droid.Resource.String.ContactProfileAdd = global::ChadderTest.Droid.Resource.String.ContactProfileAdd;
			global::ChadderLib.Droid.Resource.String.ContactProfileFingerprint = global::ChadderTest.Droid.Resource.String.ContactProfileFingerprint;
			global::ChadderLib.Droid.Resource.String.ContactProfileName = global::ChadderTest.Droid.Resource.String.ContactProfileName;
			global::ChadderLib.Droid.Resource.String.ContactProfileReport = global::ChadderTest.Droid.Resource.String.ContactProfileReport;
			global::ChadderLib.Droid.Resource.String.ContactProfileUsername = global::ChadderTest.Droid.Resource.String.ContactProfileUsername;
			global::ChadderLib.Droid.Resource.String.ContactReport = global::ChadderTest.Droid.Resource.String.ContactReport;
			global::ChadderLib.Droid.Resource.String.ContactReportConfirm = global::ChadderTest.Droid.Resource.String.ContactReportConfirm;
			global::ChadderLib.Droid.Resource.String.ContactReportMessage = global::ChadderTest.Droid.Resource.String.ContactReportMessage;
			global::ChadderLib.Droid.Resource.String.ContactReported = global::ChadderTest.Droid.Resource.String.ContactReported;
			global::ChadderLib.Droid.Resource.String.ContactUnblock = global::ChadderTest.Droid.Resource.String.ContactUnblock;
			global::ChadderLib.Droid.Resource.String.ContactsEmpty = global::ChadderTest.Droid.Resource.String.ContactsEmpty;
			global::ChadderLib.Droid.Resource.String.ContactsFilterPlaceholder = global::ChadderTest.Droid.Resource.String.ContactsFilterPlaceholder;
			global::ChadderLib.Droid.Resource.String.ContactsFindNoResults = global::ChadderTest.Droid.Resource.String.ContactsFindNoResults;
			global::ChadderLib.Droid.Resource.String.ContactsFindPlaceholder = global::ChadderTest.Droid.Resource.String.ContactsFindPlaceholder;
			global::ChadderLib.Droid.Resource.String.ContactsTabTitle = global::ChadderTest.Droid.Resource.String.ContactsTabTitle;
			global::ChadderLib.Droid.Resource.String.ConversationAttach = global::ChadderTest.Droid.Resource.String.ConversationAttach;
			global::ChadderLib.Droid.Resource.String.ConversationClearAllMessages = global::ChadderTest.Droid.Resource.String.ConversationClearAllMessages;
			global::ChadderLib.Droid.Resource.String.ConversationHide = global::ChadderTest.Droid.Resource.String.ConversationHide;
			global::ChadderLib.Droid.Resource.String.ConversationInfo = global::ChadderTest.Droid.Resource.String.ConversationInfo;
			global::ChadderLib.Droid.Resource.String.ConversationLoadOlderMessages = global::ChadderTest.Droid.Resource.String.ConversationLoadOlderMessages;
			global::ChadderLib.Droid.Resource.String.ConversationMe = global::ChadderTest.Droid.Resource.String.ConversationMe;
			global::ChadderLib.Droid.Resource.String.ConversationMessageDelete = global::ChadderTest.Droid.Resource.String.ConversationMessageDelete;
			global::ChadderLib.Droid.Resource.String.ConversationMessageDeleteRemote = global::ChadderTest.Droid.Resource.String.ConversationMessageDeleteRemote;
			global::ChadderLib.Droid.Resource.String.ConversationMessagePlaceholder = global::ChadderTest.Droid.Resource.String.ConversationMessagePlaceholder;
			global::ChadderLib.Droid.Resource.String.ConversationMessageReport = global::ChadderTest.Droid.Resource.String.ConversationMessageReport;
			global::ChadderLib.Droid.Resource.String.ConversationMessageReported = global::ChadderTest.Droid.Resource.String.ConversationMessageReported;
			global::ChadderLib.Droid.Resource.String.ConversationMessageResend = global::ChadderTest.Droid.Resource.String.ConversationMessageResend;
			global::ChadderLib.Droid.Resource.String.ConversationNoKeyConfirm = global::ChadderTest.Droid.Resource.String.ConversationNoKeyConfirm;
			global::ChadderLib.Droid.Resource.String.ConversationNoKeyMessage = global::ChadderTest.Droid.Resource.String.ConversationNoKeyMessage;
			global::ChadderLib.Droid.Resource.String.ConversationNoKeyPlaceholder = global::ChadderTest.Droid.Resource.String.ConversationNoKeyPlaceholder;
			global::ChadderLib.Droid.Resource.String.ConversationReport = global::ChadderTest.Droid.Resource.String.ConversationReport;
			global::ChadderLib.Droid.Resource.String.ConversationReportConfirm = global::ChadderTest.Droid.Resource.String.ConversationReportConfirm;
			global::ChadderLib.Droid.Resource.String.ConversationReportMessage = global::ChadderTest.Droid.Resource.String.ConversationReportMessage;
			global::ChadderLib.Droid.Resource.String.ConversationSend = global::ChadderTest.Droid.Resource.String.ConversationSend;
			global::ChadderLib.Droid.Resource.String.ConversationTakeBackAllMessages = global::ChadderTest.Droid.Resource.String.ConversationTakeBackAllMessages;
			global::ChadderLib.Droid.Resource.String.ConversationTitle = global::ChadderTest.Droid.Resource.String.ConversationTitle;
			global::ChadderLib.Droid.Resource.String.ConversationsEmpty = global::ChadderTest.Droid.Resource.String.ConversationsEmpty;
			global::ChadderLib.Droid.Resource.String.DATABASE_EXCEPTIOn = global::ChadderTest.Droid.Resource.String.DATABASE_EXCEPTIOn;
			global::ChadderLib.Droid.Resource.String.DB_FAILED_OPEN = global::ChadderTest.Droid.Resource.String.DB_FAILED_OPEN;
			global::ChadderLib.Droid.Resource.String.DEVICE_DELETED = global::ChadderTest.Droid.Resource.String.DEVICE_DELETED;
			global::ChadderLib.Droid.Resource.String.DeviceCurrent = global::ChadderTest.Droid.Resource.String.DeviceCurrent;
			global::ChadderLib.Droid.Resource.String.DeviceCurrentFingerprint = global::ChadderTest.Droid.Resource.String.DeviceCurrentFingerprint;
			global::ChadderLib.Droid.Resource.String.DeviceDelete = global::ChadderTest.Droid.Resource.String.DeviceDelete;
			global::ChadderLib.Droid.Resource.String.DeviceDeleteLoading = global::ChadderTest.Droid.Resource.String.DeviceDeleteLoading;
			global::ChadderLib.Droid.Resource.String.DeviceNoKeyMessage = global::ChadderTest.Droid.Resource.String.DeviceNoKeyMessage;
			global::ChadderLib.Droid.Resource.String.DeviceNoKeyMessageHighlighted = global::ChadderTest.Droid.Resource.String.DeviceNoKeyMessageHighlighted;
			global::ChadderLib.Droid.Resource.String.DeviceNoKeyTitle = global::ChadderTest.Droid.Resource.String.DeviceNoKeyTitle;
			global::ChadderLib.Droid.Resource.String.DevicePair = global::ChadderTest.Droid.Resource.String.DevicePair;
			global::ChadderLib.Droid.Resource.String.DevicePairAllConfirm = global::ChadderTest.Droid.Resource.String.DevicePairAllConfirm;
			global::ChadderLib.Droid.Resource.String.DevicePairAllMessage = global::ChadderTest.Droid.Resource.String.DevicePairAllMessage;
			global::ChadderLib.Droid.Resource.String.DevicePairAllTitle = global::ChadderTest.Droid.Resource.String.DevicePairAllTitle;
			global::ChadderLib.Droid.Resource.String.DevicePairConfirm = global::ChadderTest.Droid.Resource.String.DevicePairConfirm;
			global::ChadderLib.Droid.Resource.String.DevicePairLoading = global::ChadderTest.Droid.Resource.String.DevicePairLoading;
			global::ChadderLib.Droid.Resource.String.DevicePairMessage = global::ChadderTest.Droid.Resource.String.DevicePairMessage;
			global::ChadderLib.Droid.Resource.String.DevicePairTitle = global::ChadderTest.Droid.Resource.String.DevicePairTitle;
			global::ChadderLib.Droid.Resource.String.DevicePasswordChange = global::ChadderTest.Droid.Resource.String.DevicePasswordChange;
			global::ChadderLib.Droid.Resource.String.DevicePasswordChangeConfirm = global::ChadderTest.Droid.Resource.String.DevicePasswordChangeConfirm;
			global::ChadderLib.Droid.Resource.String.DevicePasswordChangeLoading = global::ChadderTest.Droid.Resource.String.DevicePasswordChangeLoading;
			global::ChadderLib.Droid.Resource.String.DevicePasswordChangeMessageNoPrevious = global::ChadderTest.Droid.Resource.String.DevicePasswordChangeMessageNoPrevious;
			global::ChadderLib.Droid.Resource.String.DevicePasswordChangeMessageWithPrevious = global::ChadderTest.Droid.Resource.String.DevicePasswordChangeMessageWithPrevious;
			global::ChadderLib.Droid.Resource.String.DevicePasswordChangeTitle = global::ChadderTest.Droid.Resource.String.DevicePasswordChangeTitle;
			global::ChadderLib.Droid.Resource.String.DevicePasswordGetMessage = global::ChadderTest.Droid.Resource.String.DevicePasswordGetMessage;
			global::ChadderLib.Droid.Resource.String.DevicePasswordGetTitle = global::ChadderTest.Droid.Resource.String.DevicePasswordGetTitle;
			global::ChadderLib.Droid.Resource.String.DevicePasswordMessage = global::ChadderTest.Droid.Resource.String.DevicePasswordMessage;
			global::ChadderLib.Droid.Resource.String.DevicePasswordRemove = global::ChadderTest.Droid.Resource.String.DevicePasswordRemove;
			global::ChadderLib.Droid.Resource.String.DevicePasswordWrong = global::ChadderTest.Droid.Resource.String.DevicePasswordWrong;
			global::ChadderLib.Droid.Resource.String.DeviceRename = global::ChadderTest.Droid.Resource.String.DeviceRename;
			global::ChadderLib.Droid.Resource.String.DeviceRenameConfirm = global::ChadderTest.Droid.Resource.String.DeviceRenameConfirm;
			global::ChadderLib.Droid.Resource.String.DeviceRenameLoading = global::ChadderTest.Droid.Resource.String.DeviceRenameLoading;
			global::ChadderLib.Droid.Resource.String.DeviceRenameMessage = global::ChadderTest.Droid.Resource.String.DeviceRenameMessage;
			global::ChadderLib.Droid.Resource.String.DevicesTabTitle = global::ChadderTest.Droid.Resource.String.DevicesTabTitle;
			global::ChadderLib.Droid.Resource.String.EMAIL_ALREADY_IN_USE = global::ChadderTest.Droid.Resource.String.EMAIL_ALREADY_IN_USE;
			global::ChadderLib.Droid.Resource.String.EncodedContent = global::ChadderTest.Droid.Resource.String.EncodedContent;
			global::ChadderLib.Droid.Resource.String.FingerprintInfo = global::ChadderTest.Droid.Resource.String.FingerprintInfo;
			global::ChadderLib.Droid.Resource.String.FingerprintInfoMessage = global::ChadderTest.Droid.Resource.String.FingerprintInfoMessage;
			global::ChadderLib.Droid.Resource.String.FingerprintLink = global::ChadderTest.Droid.Resource.String.FingerprintLink;
			global::ChadderLib.Droid.Resource.String.FingerprintLoading = global::ChadderTest.Droid.Resource.String.FingerprintLoading;
			global::ChadderLib.Droid.Resource.String.FingerprintNoKeyMessage = global::ChadderTest.Droid.Resource.String.FingerprintNoKeyMessage;
			global::ChadderLib.Droid.Resource.String.GCMNotAvailable = global::ChadderTest.Droid.Resource.String.GCMNotAvailable;
			global::ChadderLib.Droid.Resource.String.GENERAL_EXCEPTION = global::ChadderTest.Droid.Resource.String.GENERAL_EXCEPTION;
			global::ChadderLib.Droid.Resource.String.GenerateNewKey = global::ChadderTest.Droid.Resource.String.GenerateNewKey;
			global::ChadderLib.Droid.Resource.String.GenerateNewKeyConfirm = global::ChadderTest.Droid.Resource.String.GenerateNewKeyConfirm;
			global::ChadderLib.Droid.Resource.String.GenerateNewKeyLoading = global::ChadderTest.Droid.Resource.String.GenerateNewKeyLoading;
			global::ChadderLib.Droid.Resource.String.GenerateNewKeyMessage = global::ChadderTest.Droid.Resource.String.GenerateNewKeyMessage;
			global::ChadderLib.Droid.Resource.String.GenerateNewKeyTitle = global::ChadderTest.Droid.Resource.String.GenerateNewKeyTitle;
			global::ChadderLib.Droid.Resource.String.GenerateNewKeyiOS = global::ChadderTest.Droid.Resource.String.GenerateNewKeyiOS;
			global::ChadderLib.Droid.Resource.String.GhostPictureCancel = global::ChadderTest.Droid.Resource.String.GhostPictureCancel;
			global::ChadderLib.Droid.Resource.String.GhostPictureDuration = global::ChadderTest.Droid.Resource.String.GhostPictureDuration;
			global::ChadderLib.Droid.Resource.String.GhostPictureSeconds = global::ChadderTest.Droid.Resource.String.GhostPictureSeconds;
			global::ChadderLib.Droid.Resource.String.GhostPictureSend = global::ChadderTest.Droid.Resource.String.GhostPictureSend;
			global::ChadderLib.Droid.Resource.String.Hello = global::ChadderTest.Droid.Resource.String.Hello;
			global::ChadderLib.Droid.Resource.String.INVALID_CREDENTIALS = global::ChadderTest.Droid.Resource.String.INVALID_CREDENTIALS;
			global::ChadderLib.Droid.Resource.String.INVALID_EMAIL = global::ChadderTest.Droid.Resource.String.INVALID_EMAIL;
			global::ChadderLib.Droid.Resource.String.INVALID_INPUT = global::ChadderTest.Droid.Resource.String.INVALID_INPUT;
			global::ChadderLib.Droid.Resource.String.INVALID_PASSWORD = global::ChadderTest.Droid.Resource.String.INVALID_PASSWORD;
			global::ChadderLib.Droid.Resource.String.INVALID_PICTURE = global::ChadderTest.Droid.Resource.String.INVALID_PICTURE;
			global::ChadderLib.Droid.Resource.String.INVALID_USER = global::ChadderTest.Droid.Resource.String.INVALID_USER;
			global::ChadderLib.Droid.Resource.String.LicenseAgreement = global::ChadderTest.Droid.Resource.String.LicenseAgreement;
			global::ChadderLib.Droid.Resource.String.LoginAllFieldsRequired = global::ChadderTest.Droid.Resource.String.LoginAllFieldsRequired;
			global::ChadderLib.Droid.Resource.String.LoginCancel = global::ChadderTest.Droid.Resource.String.LoginCancel;
			global::ChadderLib.Droid.Resource.String.LoginForgotPassword = global::ChadderTest.Droid.Resource.String.LoginForgotPassword;
			global::ChadderLib.Droid.Resource.String.LoginForgotPasswordConfirm = global::ChadderTest.Droid.Resource.String.LoginForgotPasswordConfirm;
			global::ChadderLib.Droid.Resource.String.LoginForgotPasswordHint = global::ChadderTest.Droid.Resource.String.LoginForgotPasswordHint;
			global::ChadderLib.Droid.Resource.String.LoginForgotPasswordResult = global::ChadderTest.Droid.Resource.String.LoginForgotPasswordResult;
			global::ChadderLib.Droid.Resource.String.LoginForgotPasswordTitle = global::ChadderTest.Droid.Resource.String.LoginForgotPasswordTitle;
			global::ChadderLib.Droid.Resource.String.LoginLoading = global::ChadderTest.Droid.Resource.String.LoginLoading;
			global::ChadderLib.Droid.Resource.String.LoginLogin = global::ChadderTest.Droid.Resource.String.LoginLogin;
			global::ChadderLib.Droid.Resource.String.LoginPassword = global::ChadderTest.Droid.Resource.String.LoginPassword;
			global::ChadderLib.Droid.Resource.String.LoginRegister = global::ChadderTest.Droid.Resource.String.LoginRegister;
			global::ChadderLib.Droid.Resource.String.LoginTitle = global::ChadderTest.Droid.Resource.String.LoginTitle;
			global::ChadderLib.Droid.Resource.String.LoginUsername = global::ChadderTest.Droid.Resource.String.LoginUsername;
			global::ChadderLib.Droid.Resource.String.Logout = global::ChadderTest.Droid.Resource.String.Logout;
			global::ChadderLib.Droid.Resource.String.LogoutEraseAll = global::ChadderTest.Droid.Resource.String.LogoutEraseAll;
			global::ChadderLib.Droid.Resource.String.LogoutEraseAllConfirmationCancel = global::ChadderTest.Droid.Resource.String.LogoutEraseAllConfirmationCancel;
			global::ChadderLib.Droid.Resource.String.LogoutEraseAllConfirmationConfirm = global::ChadderTest.Droid.Resource.String.LogoutEraseAllConfirmationConfirm;
			global::ChadderLib.Droid.Resource.String.LogoutEraseAllConfirmationMessage = global::ChadderTest.Droid.Resource.String.LogoutEraseAllConfirmationMessage;
			global::ChadderLib.Droid.Resource.String.LogoutKeepData = global::ChadderTest.Droid.Resource.String.LogoutKeepData;
			global::ChadderLib.Droid.Resource.String.LogoutLoading = global::ChadderTest.Droid.Resource.String.LogoutLoading;
			global::ChadderLib.Droid.Resource.String.LogoutMessage = global::ChadderTest.Droid.Resource.String.LogoutMessage;
			global::ChadderLib.Droid.Resource.String.LogoutTitle = global::ChadderTest.Droid.Resource.String.LogoutTitle;
			global::ChadderLib.Droid.Resource.String.NOT_AUTHORIZED = global::ChadderTest.Droid.Resource.String.NOT_AUTHORIZED;
			global::ChadderLib.Droid.Resource.String.NOT_FOUND = global::ChadderTest.Droid.Resource.String.NOT_FOUND;
			global::ChadderLib.Droid.Resource.String.NameIsRequired = global::ChadderTest.Droid.Resource.String.NameIsRequired;
			global::ChadderLib.Droid.Resource.String.NotAuthorizedMessage = global::ChadderTest.Droid.Resource.String.NotAuthorizedMessage;
			global::ChadderLib.Droid.Resource.String.OFFLINE = global::ChadderTest.Droid.Resource.String.OFFLINE;
			global::ChadderLib.Droid.Resource.String.OK = global::ChadderTest.Droid.Resource.String.OK;
			global::ChadderLib.Droid.Resource.String.ONE_TIME_NOT_FOUND = global::ChadderTest.Droid.Resource.String.ONE_TIME_NOT_FOUND;
			global::ChadderLib.Droid.Resource.String.PairDeviceConfirmationMessage = global::ChadderTest.Droid.Resource.String.PairDeviceConfirmationMessage;
			global::ChadderLib.Droid.Resource.String.PairDeviceConfirmationTitle = global::ChadderTest.Droid.Resource.String.PairDeviceConfirmationTitle;
			global::ChadderLib.Droid.Resource.String.PairDeviceLoading = global::ChadderTest.Droid.Resource.String.PairDeviceLoading;
			global::ChadderLib.Droid.Resource.String.PasswordsDontMatch = global::ChadderTest.Droid.Resource.String.PasswordsDontMatch;
			global::ChadderLib.Droid.Resource.String.ProfileChangeEmailConfirm = global::ChadderTest.Droid.Resource.String.ProfileChangeEmailConfirm;
			global::ChadderLib.Droid.Resource.String.ProfileChangeEmailTitle = global::ChadderTest.Droid.Resource.String.ProfileChangeEmailTitle;
			global::ChadderLib.Droid.Resource.String.ProfileEmail = global::ChadderTest.Droid.Resource.String.ProfileEmail;
			global::ChadderLib.Droid.Resource.String.ProfileEmailMessage = global::ChadderTest.Droid.Resource.String.ProfileEmailMessage;
			global::ChadderLib.Droid.Resource.String.ProfileFAQ = global::ChadderTest.Droid.Resource.String.ProfileFAQ;
			global::ChadderLib.Droid.Resource.String.ProfileFacebookShare = global::ChadderTest.Droid.Resource.String.ProfileFacebookShare;
			global::ChadderLib.Droid.Resource.String.ProfileFacebookShareLink = global::ChadderTest.Droid.Resource.String.ProfileFacebookShareLink;
			global::ChadderLib.Droid.Resource.String.ProfileFacebookShareName = global::ChadderTest.Droid.Resource.String.ProfileFacebookShareName;
			global::ChadderLib.Droid.Resource.String.ProfileFingerprint = global::ChadderTest.Droid.Resource.String.ProfileFingerprint;
			global::ChadderLib.Droid.Resource.String.ProfileFingerprintBottomMessage = global::ChadderTest.Droid.Resource.String.ProfileFingerprintBottomMessage;
			global::ChadderLib.Droid.Resource.String.ProfileFingerprintDesc = global::ChadderTest.Droid.Resource.String.ProfileFingerprintDesc;
			global::ChadderLib.Droid.Resource.String.ProfileName = global::ChadderTest.Droid.Resource.String.ProfileName;
			global::ChadderLib.Droid.Resource.String.ProfileNameMessage = global::ChadderTest.Droid.Resource.String.ProfileNameMessage;
			global::ChadderLib.Droid.Resource.String.ProfilePictureCamera = global::ChadderTest.Droid.Resource.String.ProfilePictureCamera;
			global::ChadderLib.Droid.Resource.String.ProfilePictureGallery = global::ChadderTest.Droid.Resource.String.ProfilePictureGallery;
			global::ChadderLib.Droid.Resource.String.ProfilePictureView = global::ChadderTest.Droid.Resource.String.ProfilePictureView;
			global::ChadderLib.Droid.Resource.String.ProfilePublicName = global::ChadderTest.Droid.Resource.String.ProfilePublicName;
			global::ChadderLib.Droid.Resource.String.ProfilePublicNameMessageOff = global::ChadderTest.Droid.Resource.String.ProfilePublicNameMessageOff;
			global::ChadderLib.Droid.Resource.String.ProfilePublicNameMessageOn = global::ChadderTest.Droid.Resource.String.ProfilePublicNameMessageOn;
			global::ChadderLib.Droid.Resource.String.ProfileTabTitle = global::ChadderTest.Droid.Resource.String.ProfileTabTitle;
			global::ChadderLib.Droid.Resource.String.RegisterAllFieldsRequired = global::ChadderTest.Droid.Resource.String.RegisterAllFieldsRequired;
			global::ChadderLib.Droid.Resource.String.RegisterCancel = global::ChadderTest.Droid.Resource.String.RegisterCancel;
			global::ChadderLib.Droid.Resource.String.RegisterComplete = global::ChadderTest.Droid.Resource.String.RegisterComplete;
			global::ChadderLib.Droid.Resource.String.RegisterLoading = global::ChadderTest.Droid.Resource.String.RegisterLoading;
			global::ChadderLib.Droid.Resource.String.RegisterName = global::ChadderTest.Droid.Resource.String.RegisterName;
			global::ChadderLib.Droid.Resource.String.RegisterNameDone = global::ChadderTest.Droid.Resource.String.RegisterNameDone;
			global::ChadderLib.Droid.Resource.String.RegisterPassword = global::ChadderTest.Droid.Resource.String.RegisterPassword;
			global::ChadderLib.Droid.Resource.String.RegisterRegister = global::ChadderTest.Droid.Resource.String.RegisterRegister;
			global::ChadderLib.Droid.Resource.String.RegisterRepeatPassword = global::ChadderTest.Droid.Resource.String.RegisterRepeatPassword;
			global::ChadderLib.Droid.Resource.String.RegisterShare = global::ChadderTest.Droid.Resource.String.RegisterShare;
			global::ChadderLib.Droid.Resource.String.RegisterSkip = global::ChadderTest.Droid.Resource.String.RegisterSkip;
			global::ChadderLib.Droid.Resource.String.RegisterStart = global::ChadderTest.Droid.Resource.String.RegisterStart;
			global::ChadderLib.Droid.Resource.String.RegisterTitle = global::ChadderTest.Droid.Resource.String.RegisterTitle;
			global::ChadderLib.Droid.Resource.String.RegisterUsername = global::ChadderTest.Droid.Resource.String.RegisterUsername;
			global::ChadderLib.Droid.Resource.String.RenameDeviceCannotBeEmpty = global::ChadderTest.Droid.Resource.String.RenameDeviceCannotBeEmpty;
			global::ChadderLib.Droid.Resource.String.RenameDeviceConfirm = global::ChadderTest.Droid.Resource.String.RenameDeviceConfirm;
			global::ChadderLib.Droid.Resource.String.RenameDeviceTitle = global::ChadderTest.Droid.Resource.String.RenameDeviceTitle;
			global::ChadderLib.Droid.Resource.String.ReportPopupMessage = global::ChadderTest.Droid.Resource.String.ReportPopupMessage;
			global::ChadderLib.Droid.Resource.String.ReportProblem = global::ChadderTest.Droid.Resource.String.ReportProblem;
			global::ChadderLib.Droid.Resource.String.ResourceFlowDirection = global::ChadderTest.Droid.Resource.String.ResourceFlowDirection;
			global::ChadderLib.Droid.Resource.String.ResourceLanguage = global::ChadderTest.Droid.Resource.String.ResourceLanguage;
			global::ChadderLib.Droid.Resource.String.SCAN_INVALID = global::ChadderTest.Droid.Resource.String.SCAN_INVALID;
			global::ChadderLib.Droid.Resource.String.SCAN_NOT_FOUND = global::ChadderTest.Droid.Resource.String.SCAN_NOT_FOUND;
			global::ChadderLib.Droid.Resource.String.SCAN_WRONG_USER = global::ChadderTest.Droid.Resource.String.SCAN_WRONG_USER;
			global::ChadderLib.Droid.Resource.String.ScanFingerprint = global::ChadderTest.Droid.Resource.String.ScanFingerprint;
			global::ChadderLib.Droid.Resource.String.ScanFingerprintException = global::ChadderTest.Droid.Resource.String.ScanFingerprintException;
			global::ChadderLib.Droid.Resource.String.ScanFingerprintInvalid = global::ChadderTest.Droid.Resource.String.ScanFingerprintInvalid;
			global::ChadderLib.Droid.Resource.String.ScanFingerprintSuccess = global::ChadderTest.Droid.Resource.String.ScanFingerprintSuccess;
			global::ChadderLib.Droid.Resource.String.ScanFingerprintWrong = global::ChadderTest.Droid.Resource.String.ScanFingerprintWrong;
			global::ChadderLib.Droid.Resource.String.SearchContactLoading = global::ChadderTest.Droid.Resource.String.SearchContactLoading;
			global::ChadderLib.Droid.Resource.String.SearchContactNoResults = global::ChadderTest.Droid.Resource.String.SearchContactNoResults;
			global::ChadderLib.Droid.Resource.String.SearchContactSearch = global::ChadderTest.Droid.Resource.String.SearchContactSearch;
			global::ChadderLib.Droid.Resource.String.TourChadderMessage = global::ChadderTest.Droid.Resource.String.TourChadderMessage;
			global::ChadderLib.Droid.Resource.String.TourChadderTitle = global::ChadderTest.Droid.Resource.String.TourChadderTitle;
			global::ChadderLib.Droid.Resource.String.TourDevicesMessage = global::ChadderTest.Droid.Resource.String.TourDevicesMessage;
			global::ChadderLib.Droid.Resource.String.TourDevicesTitle = global::ChadderTest.Droid.Resource.String.TourDevicesTitle;
			global::ChadderLib.Droid.Resource.String.TourEraseMessage = global::ChadderTest.Droid.Resource.String.TourEraseMessage;
			global::ChadderLib.Droid.Resource.String.TourEraseTitle = global::ChadderTest.Droid.Resource.String.TourEraseTitle;
			global::ChadderLib.Droid.Resource.String.TourGhostsMessage = global::ChadderTest.Droid.Resource.String.TourGhostsMessage;
			global::ChadderLib.Droid.Resource.String.TourGhostsTitle = global::ChadderTest.Droid.Resource.String.TourGhostsTitle;
			global::ChadderLib.Droid.Resource.String.TourLogin = global::ChadderTest.Droid.Resource.String.TourLogin;
			global::ChadderLib.Droid.Resource.String.TourRegister = global::ChadderTest.Droid.Resource.String.TourRegister;
			global::ChadderLib.Droid.Resource.String.faq_answer_0 = global::ChadderTest.Droid.Resource.String.faq_answer_0;
			global::ChadderLib.Droid.Resource.String.faq_answer_1 = global::ChadderTest.Droid.Resource.String.faq_answer_1;
			global::ChadderLib.Droid.Resource.String.faq_answer_10 = global::ChadderTest.Droid.Resource.String.faq_answer_10;
			global::ChadderLib.Droid.Resource.String.faq_answer_2 = global::ChadderTest.Droid.Resource.String.faq_answer_2;
			global::ChadderLib.Droid.Resource.String.faq_answer_3 = global::ChadderTest.Droid.Resource.String.faq_answer_3;
			global::ChadderLib.Droid.Resource.String.faq_answer_4 = global::ChadderTest.Droid.Resource.String.faq_answer_4;
			global::ChadderLib.Droid.Resource.String.faq_answer_5 = global::ChadderTest.Droid.Resource.String.faq_answer_5;
			global::ChadderLib.Droid.Resource.String.faq_answer_6 = global::ChadderTest.Droid.Resource.String.faq_answer_6;
			global::ChadderLib.Droid.Resource.String.faq_answer_7 = global::ChadderTest.Droid.Resource.String.faq_answer_7;
			global::ChadderLib.Droid.Resource.String.faq_answer_8 = global::ChadderTest.Droid.Resource.String.faq_answer_8;
			global::ChadderLib.Droid.Resource.String.faq_answer_9 = global::ChadderTest.Droid.Resource.String.faq_answer_9;
			global::ChadderLib.Droid.Resource.String.faq_number = global::ChadderTest.Droid.Resource.String.faq_number;
			global::ChadderLib.Droid.Resource.String.faq_question_0 = global::ChadderTest.Droid.Resource.String.faq_question_0;
			global::ChadderLib.Droid.Resource.String.faq_question_1 = global::ChadderTest.Droid.Resource.String.faq_question_1;
			global::ChadderLib.Droid.Resource.String.faq_question_10 = global::ChadderTest.Droid.Resource.String.faq_question_10;
			global::ChadderLib.Droid.Resource.String.faq_question_2 = global::ChadderTest.Droid.Resource.String.faq_question_2;
			global::ChadderLib.Droid.Resource.String.faq_question_3 = global::ChadderTest.Droid.Resource.String.faq_question_3;
			global::ChadderLib.Droid.Resource.String.faq_question_4 = global::ChadderTest.Droid.Resource.String.faq_question_4;
			global::ChadderLib.Droid.Resource.String.faq_question_5 = global::ChadderTest.Droid.Resource.String.faq_question_5;
			global::ChadderLib.Droid.Resource.String.faq_question_6 = global::ChadderTest.Droid.Resource.String.faq_question_6;
			global::ChadderLib.Droid.Resource.String.faq_question_7 = global::ChadderTest.Droid.Resource.String.faq_question_7;
			global::ChadderLib.Droid.Resource.String.faq_question_8 = global::ChadderTest.Droid.Resource.String.faq_question_8;
			global::ChadderLib.Droid.Resource.String.faq_question_9 = global::ChadderTest.Droid.Resource.String.faq_question_9;
			global::ChadderLib.Droid.Resource.String.library_name = global::ChadderTest.Droid.Resource.String.library_name;
			global::Mono.Data.Sqlcipher.Resource.String.library_name = global::ChadderTest.Droid.Resource.String.library_name;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::ChadderTest.Droid.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::ChadderTest.Droid.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::ChadderTest.Droid.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::ChadderTest.Droid.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::ChadderTest.Droid.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::ChadderTest.Droid.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::ChadderTest.Droid.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::ChadderTest.Droid.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::ChadderTest.Droid.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::ChadderTest.Droid.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::ChadderTest.Droid.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::ChadderTest.Droid.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::ChadderTest.Droid.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::ChadderTest.Droid.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::ChadderTest.Droid.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::ChadderTest.Droid.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::ChadderTest.Droid.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::ChadderTest.Droid.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::ChadderTest.Droid.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::ChadderTest.Droid.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::ChadderTest.Droid.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::ChadderTest.Droid.Resource.Layout.test_suite;
			global::Xamarin.InsightsCore.Resource.String.ApplicationName = global::ChadderTest.Droid.Resource.String.ApplicationName;
			global::Xamarin.InsightsCore.Resource.String.Hello = global::ChadderTest.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_default_face = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int OptionHostName = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int OptionPort = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int OptionRemoteServer = 2131034112;
			
			// aapt resource value: 0x7f050010
			public const int OptionsButton = 2131034128;
			
			// aapt resource value: 0x7f05000b
			public const int ResultFullName = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int ResultMessage = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int ResultResultState = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int ResultRunSingleMethodTest = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int ResultStackTrace = 2131034126;
			
			// aapt resource value: 0x7f050006
			public const int ResultsFailed = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int ResultsId = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int ResultsIgnored = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int ResultsInconclusive = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int ResultsMessage = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int ResultsPassed = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int ResultsResult = 2131034116;
			
			// aapt resource value: 0x7f05000f
			public const int RunTestsButton = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int TestSuiteListView = 2131034129;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int options = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int results = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int test_result = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int test_suite = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int AccountPasswordChange = 2130968579;
			
			// aapt resource value: 0x7f04006a
			public const int AccountPasswordChangeConfirm = 2130968682;
			
			// aapt resource value: 0x7f0400d2
			public const int AccountPasswordChangeLoading = 2130968786;
			
			// aapt resource value: 0x7f0400d0
			public const int AccountPasswordChangeMessage = 2130968784;
			
			// aapt resource value: 0x7f0400d1
			public const int AccountPasswordChangeTitle = 2130968785;
			
			// aapt resource value: 0x7f040004
			public const int AddContactLink = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f0400c9
			public const int ApplicationTitle = 2130968777;
			
			// aapt resource value: 0x7f0400a3
			public const int CONNECTION_ERROR = 2130968739;
			
			// aapt resource value: 0x7f040005
			public const int ChatsTabTitle = 2130968581;
			
			// aapt resource value: 0x7f04006b
			public const int CommonAlert = 2130968683;
			
			// aapt resource value: 0x7f04006c
			public const int CommonBack = 2130968684;
			
			// aapt resource value: 0x7f040006
			public const int CommonCancel = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int CommonError = 2130968583;
			
			// aapt resource value: 0x7f040097
			public const int CommonLoading = 2130968727;
			
			// aapt resource value: 0x7f040008
			public const int CommonOkay = 2130968584;
			
			// aapt resource value: 0x7f04006d
			public const int CommonUpdating = 2130968685;
			
			// aapt resource value: 0x7f040009
			public const int CommonWarning = 2130968585;
			
			// aapt resource value: 0x7f0400b5
			public const int ConnectionNotAvailable = 2130968757;
			
			// aapt resource value: 0x7f04000a
			public const int ContactBlock = 2130968586;
			
			// aapt resource value: 0x7f040098
			public const int ContactFindTitle = 2130968728;
			
			// aapt resource value: 0x7f04006e
			public const int ContactKeyReset = 2130968686;
			
			// aapt resource value: 0x7f04006f
			public const int ContactKeyWrong = 2130968687;
			
			// aapt resource value: 0x7f040070
			public const int ContactKeyWrongTitle = 2130968688;
			
			// aapt resource value: 0x7f040099
			public const int ContactProfileAdd = 2130968729;
			
			// aapt resource value: 0x7f04000b
			public const int ContactProfileFingerprint = 2130968587;
			
			// aapt resource value: 0x7f0400b4
			public const int ContactProfileName = 2130968756;
			
			// aapt resource value: 0x7f04000c
			public const int ContactProfileReport = 2130968588;
			
			// aapt resource value: 0x7f0400b3
			public const int ContactProfileUsername = 2130968755;
			
			// aapt resource value: 0x7f04000d
			public const int ContactReport = 2130968589;
			
			// aapt resource value: 0x7f040071
			public const int ContactReportConfirm = 2130968689;
			
			// aapt resource value: 0x7f040073
			public const int ContactReportMessage = 2130968691;
			
			// aapt resource value: 0x7f040072
			public const int ContactReported = 2130968690;
			
			// aapt resource value: 0x7f040075
			public const int ContactUnblock = 2130968693;
			
			// aapt resource value: 0x7f040074
			public const int ContactsEmpty = 2130968692;
			
			// aapt resource value: 0x7f04000e
			public const int ContactsFilterPlaceholder = 2130968590;
			
			// aapt resource value: 0x7f0400ca
			public const int ContactsFindNoResults = 2130968778;
			
			// aapt resource value: 0x7f0400cb
			public const int ContactsFindPlaceholder = 2130968779;
			
			// aapt resource value: 0x7f04000f
			public const int ContactsTabTitle = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int ConversationAttach = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int ConversationClearAllMessages = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int ConversationHide = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int ConversationInfo = 2130968595;
			
			// aapt resource value: 0x7f0400e8
			public const int ConversationLoadOlderMessages = 2130968808;
			
			// aapt resource value: 0x7f0400ed
			public const int ConversationMe = 2130968813;
			
			// aapt resource value: 0x7f040014
			public const int ConversationMessageDelete = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int ConversationMessageDeleteRemote = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int ConversationMessagePlaceholder = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int ConversationMessageReport = 2130968599;
			
			// aapt resource value: 0x7f040076
			public const int ConversationMessageReported = 2130968694;
			
			// aapt resource value: 0x7f04009a
			public const int ConversationMessageResend = 2130968730;
			
			// aapt resource value: 0x7f040018
			public const int ConversationNoKeyConfirm = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int ConversationNoKeyMessage = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int ConversationNoKeyPlaceholder = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int ConversationReport = 2130968603;
			
			// aapt resource value: 0x7f04009b
			public const int ConversationReportConfirm = 2130968731;
			
			// aapt resource value: 0x7f04009c
			public const int ConversationReportMessage = 2130968732;
			
			// aapt resource value: 0x7f04001c
			public const int ConversationSend = 2130968604;
			
			// aapt resource value: 0x7f0400e9
			public const int ConversationTakeBackAllMessages = 2130968809;
			
			// aapt resource value: 0x7f040077
			public const int ConversationTitle = 2130968695;
			
			// aapt resource value: 0x7f040069
			public const int ConversationsEmpty = 2130968681;
			
			// aapt resource value: 0x7f0400a4
			public const int DATABASE_EXCEPTIOn = 2130968740;
			
			// aapt resource value: 0x7f0400a5
			public const int DB_FAILED_OPEN = 2130968741;
			
			// aapt resource value: 0x7f0400a6
			public const int DEVICE_DELETED = 2130968742;
			
			// aapt resource value: 0x7f04001d
			public const int DeviceCurrent = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int DeviceCurrentFingerprint = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int DeviceDelete = 2130968607;
			
			// aapt resource value: 0x7f04009d
			public const int DeviceDeleteLoading = 2130968733;
			
			// aapt resource value: 0x7f0400ee
			public const int DeviceNoKeyMessage = 2130968814;
			
			// aapt resource value: 0x7f0400ef
			public const int DeviceNoKeyMessageHighlighted = 2130968815;
			
			// aapt resource value: 0x7f0400f0
			public const int DeviceNoKeyTitle = 2130968816;
			
			// aapt resource value: 0x7f040020
			public const int DevicePair = 2130968608;
			
			// aapt resource value: 0x7f040078
			public const int DevicePairAllConfirm = 2130968696;
			
			// aapt resource value: 0x7f040036
			public const int DevicePairAllMessage = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int DevicePairAllTitle = 2130968631;
			
			// aapt resource value: 0x7f0400b6
			public const int DevicePairConfirm = 2130968758;
			
			// aapt resource value: 0x7f040079
			public const int DevicePairLoading = 2130968697;
			
			// aapt resource value: 0x7f0400b7
			public const int DevicePairMessage = 2130968759;
			
			// aapt resource value: 0x7f0400b8
			public const int DevicePairTitle = 2130968760;
			
			// aapt resource value: 0x7f040021
			public const int DevicePasswordChange = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int DevicePasswordChangeConfirm = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int DevicePasswordChangeLoading = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int DevicePasswordChangeMessageNoPrevious = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int DevicePasswordChangeMessageWithPrevious = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int DevicePasswordChangeTitle = 2130968614;
			
			// aapt resource value: 0x7f040028
			public const int DevicePasswordGetMessage = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int DevicePasswordGetTitle = 2130968617;
			
			// aapt resource value: 0x7f040027
			public const int DevicePasswordMessage = 2130968615;
			
			// aapt resource value: 0x7f04007a
			public const int DevicePasswordRemove = 2130968698;
			
			// aapt resource value: 0x7f04002a
			public const int DevicePasswordWrong = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int DeviceRename = 2130968619;
			
			// aapt resource value: 0x7f04009e
			public const int DeviceRenameConfirm = 2130968734;
			
			// aapt resource value: 0x7f04009f
			public const int DeviceRenameLoading = 2130968735;
			
			// aapt resource value: 0x7f0400a0
			public const int DeviceRenameMessage = 2130968736;
			
			// aapt resource value: 0x7f04002c
			public const int DevicesTabTitle = 2130968620;
			
			// aapt resource value: 0x7f0400bb
			public const int EMAIL_ALREADY_IN_USE = 2130968763;
			
			// aapt resource value: 0x7f0400d6
			public const int EncodedContent = 2130968790;
			
			// aapt resource value: 0x7f04002d
			public const int FingerprintInfo = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int FingerprintInfoMessage = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int FingerprintLink = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int FingerprintLoading = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int FingerprintNoKeyMessage = 2130968625;
			
			// aapt resource value: 0x7f0400b9
			public const int GCMNotAvailable = 2130968761;
			
			// aapt resource value: 0x7f0400a7
			public const int GENERAL_EXCEPTION = 2130968743;
			
			// aapt resource value: 0x7f040032
			public const int GenerateNewKey = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int GenerateNewKeyConfirm = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int GenerateNewKeyLoading = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int GenerateNewKeyMessage = 2130968629;
			
			// aapt resource value: 0x7f040038
			public const int GenerateNewKeyTitle = 2130968632;
			
			// aapt resource value: 0x7f0400a1
			public const int GenerateNewKeyiOS = 2130968737;
			
			// aapt resource value: 0x7f0400c8
			public const int GhostPictureCancel = 2130968776;
			
			// aapt resource value: 0x7f0400c6
			public const int GhostPictureDuration = 2130968774;
			
			// aapt resource value: 0x7f0400cd
			public const int GhostPictureSeconds = 2130968781;
			
			// aapt resource value: 0x7f0400c7
			public const int GhostPictureSend = 2130968775;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f0400b2
			public const int INVALID_CREDENTIALS = 2130968754;
			
			// aapt resource value: 0x7f0400bc
			public const int INVALID_EMAIL = 2130968764;
			
			// aapt resource value: 0x7f0400a8
			public const int INVALID_INPUT = 2130968744;
			
			// aapt resource value: 0x7f0400a9
			public const int INVALID_PASSWORD = 2130968745;
			
			// aapt resource value: 0x7f0400cc
			public const int INVALID_PICTURE = 2130968780;
			
			// aapt resource value: 0x7f0400bd
			public const int INVALID_USER = 2130968765;
			
			// aapt resource value: 0x7f0400dd
			public const int LicenseAgreement = 2130968797;
			
			// aapt resource value: 0x7f0400a2
			public const int LoginAllFieldsRequired = 2130968738;
			
			// aapt resource value: 0x7f0400d3
			public const int LoginCancel = 2130968787;
			
			// aapt resource value: 0x7f0400c0
			public const int LoginForgotPassword = 2130968768;
			
			// aapt resource value: 0x7f0400c1
			public const int LoginForgotPasswordConfirm = 2130968769;
			
			// aapt resource value: 0x7f0400c4
			public const int LoginForgotPasswordHint = 2130968772;
			
			// aapt resource value: 0x7f0400c3
			public const int LoginForgotPasswordResult = 2130968771;
			
			// aapt resource value: 0x7f0400c2
			public const int LoginForgotPasswordTitle = 2130968770;
			
			// aapt resource value: 0x7f040039
			public const int LoginLoading = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int LoginLogin = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int LoginPassword = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int LoginRegister = 2130968636;
			
			// aapt resource value: 0x7f0400e6
			public const int LoginTitle = 2130968806;
			
			// aapt resource value: 0x7f04003d
			public const int LoginUsername = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int Logout = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int LogoutEraseAll = 2130968639;
			
			// aapt resource value: 0x7f0400ea
			public const int LogoutEraseAllConfirmationCancel = 2130968810;
			
			// aapt resource value: 0x7f0400eb
			public const int LogoutEraseAllConfirmationConfirm = 2130968811;
			
			// aapt resource value: 0x7f0400ec
			public const int LogoutEraseAllConfirmationMessage = 2130968812;
			
			// aapt resource value: 0x7f040040
			public const int LogoutKeepData = 2130968640;
			
			// aapt resource value: 0x7f040092
			public const int LogoutLoading = 2130968722;
			
			// aapt resource value: 0x7f040041
			public const int LogoutMessage = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int LogoutTitle = 2130968642;
			
			// aapt resource value: 0x7f0400aa
			public const int NOT_AUTHORIZED = 2130968746;
			
			// aapt resource value: 0x7f0400ab
			public const int NOT_FOUND = 2130968747;
			
			// aapt resource value: 0x7f0400d7
			public const int NameIsRequired = 2130968791;
			
			// aapt resource value: 0x7f0400c5
			public const int NotAuthorizedMessage = 2130968773;
			
			// aapt resource value: 0x7f0400ac
			public const int OFFLINE = 2130968748;
			
			// aapt resource value: 0x7f0400ad
			public const int OK = 2130968749;
			
			// aapt resource value: 0x7f0400ae
			public const int ONE_TIME_NOT_FOUND = 2130968750;
			
			// aapt resource value: 0x7f040043
			public const int PairDeviceConfirmationMessage = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int PairDeviceConfirmationTitle = 2130968644;
			
			// aapt resource value: 0x7f040045
			public const int PairDeviceLoading = 2130968645;
			
			// aapt resource value: 0x7f040046
			public const int PasswordsDontMatch = 2130968646;
			
			// aapt resource value: 0x7f0400be
			public const int ProfileChangeEmailConfirm = 2130968766;
			
			// aapt resource value: 0x7f0400bf
			public const int ProfileChangeEmailTitle = 2130968767;
			
			// aapt resource value: 0x7f040047
			public const int ProfileEmail = 2130968647;
			
			// aapt resource value: 0x7f040048
			public const int ProfileEmailMessage = 2130968648;
			
			// aapt resource value: 0x7f04004b
			public const int ProfileFAQ = 2130968651;
			
			// aapt resource value: 0x7f040049
			public const int ProfileFacebookShare = 2130968649;
			
			// aapt resource value: 0x7f04004a
			public const int ProfileFacebookShareLink = 2130968650;
			
			// aapt resource value: 0x7f040093
			public const int ProfileFacebookShareName = 2130968723;
			
			// aapt resource value: 0x7f040094
			public const int ProfileFingerprint = 2130968724;
			
			// aapt resource value: 0x7f0400ba
			public const int ProfileFingerprintBottomMessage = 2130968762;
			
			// aapt resource value: 0x7f040095
			public const int ProfileFingerprintDesc = 2130968725;
			
			// aapt resource value: 0x7f04004c
			public const int ProfileName = 2130968652;
			
			// aapt resource value: 0x7f04004d
			public const int ProfileNameMessage = 2130968653;
			
			// aapt resource value: 0x7f04004e
			public const int ProfilePictureCamera = 2130968654;
			
			// aapt resource value: 0x7f04004f
			public const int ProfilePictureGallery = 2130968655;
			
			// aapt resource value: 0x7f040050
			public const int ProfilePictureView = 2130968656;
			
			// aapt resource value: 0x7f040051
			public const int ProfilePublicName = 2130968657;
			
			// aapt resource value: 0x7f040052
			public const int ProfilePublicNameMessageOff = 2130968658;
			
			// aapt resource value: 0x7f040053
			public const int ProfilePublicNameMessageOn = 2130968659;
			
			// aapt resource value: 0x7f040054
			public const int ProfileTabTitle = 2130968660;
			
			// aapt resource value: 0x7f040055
			public const int RegisterAllFieldsRequired = 2130968661;
			
			// aapt resource value: 0x7f040056
			public const int RegisterCancel = 2130968662;
			
			// aapt resource value: 0x7f0400d8
			public const int RegisterComplete = 2130968792;
			
			// aapt resource value: 0x7f040057
			public const int RegisterLoading = 2130968663;
			
			// aapt resource value: 0x7f040058
			public const int RegisterName = 2130968664;
			
			// aapt resource value: 0x7f0400dc
			public const int RegisterNameDone = 2130968796;
			
			// aapt resource value: 0x7f040059
			public const int RegisterPassword = 2130968665;
			
			// aapt resource value: 0x7f04005a
			public const int RegisterRegister = 2130968666;
			
			// aapt resource value: 0x7f04005b
			public const int RegisterRepeatPassword = 2130968667;
			
			// aapt resource value: 0x7f0400d9
			public const int RegisterShare = 2130968793;
			
			// aapt resource value: 0x7f0400da
			public const int RegisterSkip = 2130968794;
			
			// aapt resource value: 0x7f0400db
			public const int RegisterStart = 2130968795;
			
			// aapt resource value: 0x7f0400e7
			public const int RegisterTitle = 2130968807;
			
			// aapt resource value: 0x7f04005c
			public const int RegisterUsername = 2130968668;
			
			// aapt resource value: 0x7f04005d
			public const int RenameDeviceCannotBeEmpty = 2130968669;
			
			// aapt resource value: 0x7f04005e
			public const int RenameDeviceConfirm = 2130968670;
			
			// aapt resource value: 0x7f04005f
			public const int RenameDeviceTitle = 2130968671;
			
			// aapt resource value: 0x7f040096
			public const int ReportPopupMessage = 2130968726;
			
			// aapt resource value: 0x7f040060
			public const int ReportProblem = 2130968672;
			
			// aapt resource value: 0x7f040061
			public const int ResourceFlowDirection = 2130968673;
			
			// aapt resource value: 0x7f040062
			public const int ResourceLanguage = 2130968674;
			
			// aapt resource value: 0x7f0400af
			public const int SCAN_INVALID = 2130968751;
			
			// aapt resource value: 0x7f0400b0
			public const int SCAN_NOT_FOUND = 2130968752;
			
			// aapt resource value: 0x7f0400b1
			public const int SCAN_WRONG_USER = 2130968753;
			
			// aapt resource value: 0x7f040063
			public const int ScanFingerprint = 2130968675;
			
			// aapt resource value: 0x7f040064
			public const int ScanFingerprintException = 2130968676;
			
			// aapt resource value: 0x7f040065
			public const int ScanFingerprintInvalid = 2130968677;
			
			// aapt resource value: 0x7f0400cf
			public const int ScanFingerprintSuccess = 2130968783;
			
			// aapt resource value: 0x7f0400ce
			public const int ScanFingerprintWrong = 2130968782;
			
			// aapt resource value: 0x7f040066
			public const int SearchContactLoading = 2130968678;
			
			// aapt resource value: 0x7f040067
			public const int SearchContactNoResults = 2130968679;
			
			// aapt resource value: 0x7f040068
			public const int SearchContactSearch = 2130968680;
			
			// aapt resource value: 0x7f0400de
			public const int TourChadderMessage = 2130968798;
			
			// aapt resource value: 0x7f0400df
			public const int TourChadderTitle = 2130968799;
			
			// aapt resource value: 0x7f0400e0
			public const int TourDevicesMessage = 2130968800;
			
			// aapt resource value: 0x7f0400e1
			public const int TourDevicesTitle = 2130968801;
			
			// aapt resource value: 0x7f0400e2
			public const int TourEraseMessage = 2130968802;
			
			// aapt resource value: 0x7f0400e3
			public const int TourEraseTitle = 2130968803;
			
			// aapt resource value: 0x7f0400e4
			public const int TourGhostsMessage = 2130968804;
			
			// aapt resource value: 0x7f0400e5
			public const int TourGhostsTitle = 2130968805;
			
			// aapt resource value: 0x7f0400d4
			public const int TourLogin = 2130968788;
			
			// aapt resource value: 0x7f0400d5
			public const int TourRegister = 2130968789;
			
			// aapt resource value: 0x7f04007b
			public const int faq_answer_0 = 2130968699;
			
			// aapt resource value: 0x7f04007c
			public const int faq_answer_1 = 2130968700;
			
			// aapt resource value: 0x7f04007d
			public const int faq_answer_10 = 2130968701;
			
			// aapt resource value: 0x7f04007e
			public const int faq_answer_2 = 2130968702;
			
			// aapt resource value: 0x7f04007f
			public const int faq_answer_3 = 2130968703;
			
			// aapt resource value: 0x7f040080
			public const int faq_answer_4 = 2130968704;
			
			// aapt resource value: 0x7f040081
			public const int faq_answer_5 = 2130968705;
			
			// aapt resource value: 0x7f040082
			public const int faq_answer_6 = 2130968706;
			
			// aapt resource value: 0x7f040083
			public const int faq_answer_7 = 2130968707;
			
			// aapt resource value: 0x7f040084
			public const int faq_answer_8 = 2130968708;
			
			// aapt resource value: 0x7f040085
			public const int faq_answer_9 = 2130968709;
			
			// aapt resource value: 0x7f040086
			public const int faq_number = 2130968710;
			
			// aapt resource value: 0x7f040087
			public const int faq_question_0 = 2130968711;
			
			// aapt resource value: 0x7f040088
			public const int faq_question_1 = 2130968712;
			
			// aapt resource value: 0x7f040089
			public const int faq_question_10 = 2130968713;
			
			// aapt resource value: 0x7f04008a
			public const int faq_question_2 = 2130968714;
			
			// aapt resource value: 0x7f04008b
			public const int faq_question_3 = 2130968715;
			
			// aapt resource value: 0x7f04008c
			public const int faq_question_4 = 2130968716;
			
			// aapt resource value: 0x7f04008d
			public const int faq_question_5 = 2130968717;
			
			// aapt resource value: 0x7f04008e
			public const int faq_question_6 = 2130968718;
			
			// aapt resource value: 0x7f04008f
			public const int faq_question_7 = 2130968719;
			
			// aapt resource value: 0x7f040090
			public const int faq_question_8 = 2130968720;
			
			// aapt resource value: 0x7f040091
			public const int faq_question_9 = 2130968721;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
